import Providers from "./components/Providers";

import { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "제목 미정",
  description: "Generated by create next app",
};

export default function RootLayout({
  children, // will be a page or nested layout
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko-kr" className=" w-full h-full ">
      <body className="w-screen h-screen bg-sky-100">
        {/* <AuthContext> */}

        <Providers>{children}</Providers>
        {/* </AuthContext> */}
      </body>
    </html>
  );
}
